config/routes.rb
Rails.application.routes.draw do
  resources :book_marks

  root 'book_marks#index'

  namespace :api do
    namespace :v1 do
      resources :book_marks
    end
  end

end

app/models/book_mark.rb
class BookMark < ActiveRecord::Base
  validates :link_path, presence: true, :format => {:with => URI.regexp}
  # default_scope { order('updated_at desc') }
  # validates_format_of :link_path, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i
end

app/controllers/api/v1/book_marks_controller.rb
class Api::V1::BookMarksController < ApplicationController

  before_filter :authentication

  def index
    p '======================= Index'
    @book_marks = BookMark.all
    render json: @book_marks
  end

  def create

  end


  private

    def authentication
      if request.headers['key'] == 'https://github.com/sajjadmurtaza49-jhdjkf874324b3248b4sdf'
        p '======================= Authentication Pass.'
        true
      else
        p '======================= Authentication failed.'
        render json: 'Authentication failed.'
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_marks_controller.rb
class BookMarksController < ApplicationController
  before_action :set_book_mark, only: [:destroy, :edit, :update]

  def index
    @book_marks = BookMark.all.order('title asc')
  end


  def create
    @book_mark = BookMark.new(book_mark_params)
    if @book_mark.title.split(/\s+/).last == "+"
      @book_mark.save
    end
  end

  def edit

  end

  def update
    @book_mark.update(book_mark_params)
  end

  def destroy
    if params[:delete] == 'del'
      @book_mark.destroy
    end
  end

  private
    def set_book_mark
      @book_mark = BookMark.find(params[:id])
    end

    def book_mark_params
      params.require(:book_mark).permit(:title, :link_path, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_marks_helper.rb
module BookMarksHelper
end

app/views/book_marks/_book_mark.html.slim
.record id="book_mark_#{book_mark.id}"
  p
    b
      - title = book_mark.title
      - title = title[/(.*)\s/,1]
      = link_to title, book_mark.link_path, target: '_blank'
      span.del
        = text_field_tag :delete, '', 'data-load-event-url' => book_mark_path(book_mark), placeholder: "#{index}"

      br
    = book_mark.link_path
    br
    = book_mark.description
  br
  hr

app/views/book_marks/_form.html.slim
= form_for @book_mark, html: {remote: true} do |f|

  .field
    = f.label :link_path, class: 'label'
    br
    = f.text_field :link_path, placeholder: 'e.g. https://www.sajjadmurtaza.com'

  .field
    = f.label :title, class: 'label'
    br
    = f.text_field :title, placeholder: 'e.g. Sajjad Murtaza'

  .field
    = f.label :description, class: 'label'
    br
    = f.text_area :description, placeholder: 'e.g. Personal WebSite'

  .actions
    = f.submit

app/views/book_marks/create.js.erb
<% if @book_mark.id.present? %>
	$('.object_book_marks').prepend($("<%= escape_javascript render(partial: "book_mark", locals: {book_mark: @book_mark, index: 'refresh'}) %>").hide().fadeIn(1000));
	$('#book_mark_link_path').val("");
    $('#book_mark_title').val("");
<% else %>
	alert("Sorry dude you can't, Its only for Admin ");
	$('#book_mark_link_path').val("");
    $('#book_mark_title').val("");
<% end %>

app/views/book_marks/destroy.js.erb
<% if @book_mark.destroyed?%>
    $("#book_mark_<%=@book_mark.id%>").fadeOut(1000, function(){
        $(this).remove();
    });
<% end %>

app/views/book_marks/edit.html.slim
h1 Editing book_mark

== render 'form'

= link_to 'Show', @book_mark
'|
= link_to 'Back', book_marks_path

app/views/book_marks/edit.js.erb
$('.form').hide();
$('.edit_form').append("<%= j render(:partial => 'form') %>").show().hide().fadeIn(1300);

app/views/book_marks/index.html.slim
.object_book_mark_form
  .container
    .heading
      h2
        | Book Mark
    .form
      = form_for BookMark.new, url: book_marks_path, html: {remote: true} do |f|

        .field
          = f.label :link_path, class: 'label'
          br
          = f.text_field :link_path, placeholder: 'e.g. https://www.sajjadmurtaza.com'

        .field
          = f.label :title, class: 'label'
          br
          = f.text_field :title, placeholder: 'e.g. Sajjad Murtaza'

        .field
          = f.label :description, class: 'label'
          br
          = f.text_area :description, placeholder: 'e.g. Personal WebSite'

        .actions
          = f.submit
    .edit_form
  hr width='32%'

  .object_book_marks.container-list

    - @book_marks.each_with_index do |book_mark, index|
      = render partial: 'book_marks/book_mark', locals: {book_mark: book_mark, index: index+1}

app/views/book_marks/new.html.slim
h1 New book_mark

== render 'form'

= link_to 'Back', book_marks_path

app/views/book_marks/show.html.slim
p#notice = notice

p
  strong Title:
  = @book_mark.title
p
  strong Url:
  = @book_mark.url

= link_to 'Edit', edit_book_mark_path(@book_mark)
'|
= link_to 'Back', book_marks_path

app/views/book_marks/update.js.erb
$(window.location.replace("/"));

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'Bookmark-icon.png' %>
  <title>BookMark - Sajjad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div id="email">
  <strong>Email: </strong><a href="mailto:sajjadmurtaza.nxb@gmail.com" target="_top">sajjadmurtaza.nxb@gmail.com</a>
</div>

</body>
</html>